package com.chic.lexer

import com.intellij.lexer.FlexAdapter

/**
 * Wraps the JFlex-generated [_ChicLexer] in IntelliJ's [FlexAdapter].
 *
 * [_ChicLexer] is generated by the `generateChicLexer` Gradle task from
 * `src/main/flex/ChicLexer.flex`.  Run `./gradlew generateChicLexer` before
 * compiling if the generated source is missing.
 */
class ChicLexerAdapter : FlexAdapter(_ChicLexer(null))
